# Generated by Django 4.2.7 on 2025-07-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom en français')),
                ('name_wo', models.CharField(max_length=100, verbose_name='Nom en wolof')),
                ('scientific_name', models.CharField(blank=True, max_length=100, verbose_name='Nom scientifique')),
                ('category', models.CharField(choices=[('cereales', 'Céréales'), ('legumineuses', 'Légumineuses'), ('legumes', 'Légumes'), ('fruits', 'Fruits'), ('tubercules', 'Tubercules')], max_length=50)),
                ('growing_season', models.CharField(max_length=100, verbose_name='Saison de culture')),
                ('planting_period', models.CharField(max_length=100, verbose_name='Période de plantation')),
                ('harvest_period', models.CharField(max_length=100, verbose_name='Période de récolte')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('description_fr', models.TextField(blank=True)),
                ('description_wo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='CropTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fr', models.CharField(max_length=200, verbose_name='Titre en français')),
                ('title_wo', models.CharField(max_length=200, verbose_name='Titre en wolof')),
                ('content_fr', models.TextField(verbose_name='Contenu en français')),
                ('content_wo', models.TextField(verbose_name='Contenu en wolof')),
                ('tip_type', models.CharField(choices=[('planting', 'Plantation'), ('care', 'Entretien'), ('fertilization', 'Fertilisation'), ('irrigation', 'Irrigation'), ('pest_control', 'Lutte antiparasitaire'), ('harvest', 'Récolte'), ('storage', 'Conservation')], max_length=50)),
                ('season', models.CharField(blank=True, max_length=50)),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Conseil urgent')),
                ('priority', models.IntegerField(choices=[(1, 'Faible'), (2, 'Normale'), (3, 'Élevée'), (4, 'Critique')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conseil agricole',
                'verbose_name_plural': 'Conseils agricoles',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
