# Generated by Django 4.2.7 on 2025-07-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='location',
            new_name='region',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
